on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

name: pages

env:
  PYTHONUNBUFFERED: "1"

jobs:
  build-sphinx-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure pages
        uses: actions/configure-pages@v5

      - uses: actions/cache@v4
        with:
          path: |
            _build/.jupyter_cache
            _build/jupyter_execute
          key: pages-${{ runner.os }}-${{ hashFiles('docs/source/notebooks/**') }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Setup Python
        shell: bash
        run: uv venv

      - name: Install Python dependencies
        run: uv pip install .[docs]

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Generate HTML
        run: |
          uv run sphinx-build -j auto \
            -d _build/doctrees docs/source _build/html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

  deploy:
    if: contains(fromJSON('["main", "master"]'), github.ref_name) && github.event_name != 'pull_request'
    needs: build-sphinx-site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
