on:
  pull_request:
  push:
    branches: [main, master]

name: pre-commit

env:
  PYTHONUNBUFFERED: "1"
  UV_SYSTEM_PYTHON: 1

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pre-commit checks
        uses: ccao-data/actions/pre-commit@main
